require_relative 'tasks/appender.rb'
require_relative 'tasks/catalogue_maker.rb'
require_relative 'tasks/convertor.rb'
require_relative 'tasks/index_dup_remover.rb'
require_relative 'tasks/light_curve_plotter.rb'
require_relative 'tasks/merger.rb'
require_relative 'tasks/slicer.rb'
require_relative 'tasks/transformer.rb'
